server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: mzOt2TDkEafC9ywOlt68IBVvfFZPf3Er
            client-secret: P2IhTOvfKivuwJJMCRtDqfCYFuoU1GvWqcgsE5Gr-I7JENiP8frbdO_QlFJNsAnT
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://beetle-tracker.eu.auth0.com/
